sudo: required
services:
  - docker

before_install:
  - docker build -t mayank/docker-react -f Dockerfile.dev .

script:
  # here -- --coverage will not keep the container hanging .. but will exit with exit code 0
  - docker run mayank/docker-react npm run test -- --coverage