version: '3'
services:
  web:
    build:
      # specifies the folder where docker files are
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # '-' specifies an array of data.
      - /usr/app/node_modules
      - .:/usr/app
  tests:
    build:
      # specifies the folder where docker files are
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]